"""
Fact Table - Structured SPO Triple Storage

Implements the Knowledge Graph Fact Schema from revisi.md Section 9:
- 8 Entity Types (METHOD, CONCEPT, DOMAIN, FINDING, DATASET, METRIC, PAPER, CONSTRAINT)
- 12+ Predicate Types (USES_METHOD, PROPOSES, APPLIES_TO, ACHIEVES, etc.)
- CRUD operations for SPO triples
- Query interface for Rule Engine consumption

References:
    - Cooper, H. (1998). Synthesizing Research
    - Ji, S., et al. (2021). A Survey on Knowledge Graphs
    - revisi.md Section 9: Skema Fakta Knowledge Graph (Tabel SPO)
"""

from __future__ import annotations

import threading
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple

from loguru import logger


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class EntityType(str, Enum):
    """8 tipe entitas sesuai revisi.md Section 9"""
    METHOD = "METHOD"           # Metode/algoritma/teknik
    CONCEPT = "CONCEPT"         # Konsep/teori/framework
    DOMAIN = "DOMAIN"           # Domain/bidang penerapan
    FINDING = "FINDING"         # Temuan empiris
    DATASET = "DATASET"         # Dataset yang digunakan
    METRIC = "METRIC"           # Metrik evaluasi
    PAPER = "PAPER"             # Paper sumber
    CONSTRAINT = "CONSTRAINT"   # Keterbatasan/syarat


class PredicateType(str, Enum):
    """12+ tipe relasi (edge/predikat) sesuai revisi.md Section 9"""
    USES_METHOD = "USES_METHOD"             # PAPER → METHOD
    PROPOSES = "PROPOSES"                   # PAPER → METHOD/CONCEPT
    APPLIES_TO = "APPLIES_TO"              # METHOD → DOMAIN
    ACHIEVES = "ACHIEVES"                  # METHOD → FINDING
    REQUIRES_RESOURCE = "REQUIRES_RESOURCE" # METHOD → CONSTRAINT
    REQUIRES_DATA = "REQUIRES_DATA"        # METHOD → CONSTRAINT
    IMPROVES = "IMPROVES"                  # METHOD → METHOD
    CONTRADICTS = "CONTRADICTS"            # FINDING → FINDING
    EXTENDS = "EXTENDS"                    # CONCEPT → CONCEPT
    EVALUATED_ON = "EVALUATED_ON"          # METHOD → DATASET
    HAS_CONSTRAINT = "HAS_CONSTRAINT"      # DOMAIN → CONSTRAINT
    DISCUSSES = "DISCUSSES"                # PAPER → CONCEPT

    # Inferred predicates (generated by Rule Engine)
    INFEASIBLE_FOR = "INFEASIBLE_FOR"      # METHOD → DOMAIN (inferred via F1)
    CORRELATES_WITH = "CORRELATES_WITH"    # FINDING → FINDING (downgraded from CAUSAL)


class Verdict(str, Enum):
    """Rule Engine verdicts (revisi.md Section 7)"""
    PASS = "PASS"       # Output lolos semua aturan
    FLAG = "FLAG"       # Melanggar aturan non-kritis → perlu review manusia
    REJECT = "REJECT"   # Melanggar aturan kritis → jangan tampilkan


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------

@dataclass
class Entity:
    """Represents a node in the Knowledge Graph"""
    entity_id: str
    entity_type: EntityType
    name: str
    properties: Dict[str, Any] = field(default_factory=dict)
    source_paper: Optional[str] = None  # paper_id asal entity ini ditemukan

    def __hash__(self):
        return hash(self.entity_id)

    def __eq__(self, other):
        if isinstance(other, Entity):
            return self.entity_id == other.entity_id
        return False


@dataclass
class Fact:
    """
    Represents an SPO triple (Subject-Predicate-Object).
    
    Example from revisi.md:
        Fact(
            subject_id="CNN_Segmentation",
            predicate=PredicateType.ACHIEVES,
            object_id="Dice_92.3%",
            source="Sec. 4, p.8",
            confidence=0.95
        )
    """
    fact_id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    subject_id: str = ""
    predicate: PredicateType = PredicateType.DISCUSSES
    object_id: str = ""
    source: str = ""            # "Sec. 3, p.5" — lokasi di paper
    source_paper: str = ""      # paper_id
    confidence: float = 1.0     # 0.0 - 1.0
    is_inferred: bool = False   # True jika dihasilkan oleh Rule Engine
    inferred_by_rule: str = ""  # e.g. "F1" jika is_inferred=True
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "fact_id": self.fact_id,
            "subject_id": self.subject_id,
            "predicate": self.predicate.value,
            "object_id": self.object_id,
            "source": self.source,
            "source_paper": self.source_paper,
            "confidence": self.confidence,
            "is_inferred": self.is_inferred,
            "inferred_by_rule": self.inferred_by_rule,
            "metadata": self.metadata,
        }


# ---------------------------------------------------------------------------
# FactTable
# ---------------------------------------------------------------------------

class FactTable:
    """
    Structured storage for SPO triples extracted from research papers.
    
    Provides:
    - CRUD operations for entities and facts
    - Query interface for Rule Engine (query by subject, predicate, object)
    - Contradiction detection (FINDING ↔ FINDING with CONTRADICTS predicate)
    - Statistics for API response
    
    This is the "Fact Base" that feeds into the Rule Engine
    (revisi.md Section 7: Facts (KG) + Rules → Inference → Accept/Reject/Flag)
    """

    def __init__(self):
        # Entity storage: entity_id → Entity
        self._entities: Dict[str, Entity] = {}
        
        # Fact storage: fact_id → Fact
        self._facts: Dict[str, Fact] = {}
        
        # Indexes for fast lookup
        self._by_subject: Dict[str, Set[str]] = {}   # subject_id → {fact_ids}
        self._by_predicate: Dict[PredicateType, Set[str]] = {}  # predicate → {fact_ids}
        self._by_object: Dict[str, Set[str]] = {}    # object_id → {fact_ids}
        self._by_paper: Dict[str, Set[str]] = {}     # paper_id → {fact_ids}

        # Guards all mutations so the table can be populated from multiple
        # extraction threads safely. Reentrant because get_or_create_entity
        # calls add_entity while already holding the lock.
        self._lock = threading.RLock()
        
        logger.info("FactTable initialized")

    # -----------------------------------------------------------------------
    # Entity CRUD
    # -----------------------------------------------------------------------

    def add_entity(self, entity: Entity) -> str:
        """Add an entity to the table. Returns entity_id."""
        with self._lock:
            self._entities[entity.entity_id] = entity
        logger.debug(f"Added entity: {entity.entity_id} ({entity.entity_type.value}): {entity.name}")
        return entity.entity_id

    def get_entity(self, entity_id: str) -> Optional[Entity]:
        """Get entity by ID."""
        return self._entities.get(entity_id)

    def find_entities(
        self,
        entity_type: Optional[EntityType] = None,
        name_contains: Optional[str] = None,
        source_paper: Optional[str] = None,
    ) -> List[Entity]:
        """Find entities matching filters."""
        results = list(self._entities.values())

        if entity_type is not None:
            results = [e for e in results if e.entity_type == entity_type]
        if name_contains is not None:
            needle = name_contains.lower()
            results = [e for e in results if needle in e.name.lower()]
        if source_paper is not None:
            results = [e for e in results if e.source_paper == source_paper]

        return results

    def get_or_create_entity(
        self,
        name: str,
        entity_type: EntityType,
        source_paper: Optional[str] = None,
        properties: Optional[Dict[str, Any]] = None,
    ) -> Entity:
        """Find existing entity by name+type or create a new one."""
        with self._lock:
            # Check for existing with same name and type
            for e in self._entities.values():
                if e.name.lower() == name.lower() and e.entity_type == entity_type:
                    return e

            # Create new
            entity_id = f"{entity_type.value.lower()}_{name.lower().replace(' ', '_')[:30]}_{uuid.uuid4().hex[:6]}"
            entity = Entity(
                entity_id=entity_id,
                entity_type=entity_type,
                name=name,
                properties=properties or {},
                source_paper=source_paper,
            )
            self.add_entity(entity)
            return entity

    # -----------------------------------------------------------------------
    # Fact CRUD
    # -----------------------------------------------------------------------

    def add_fact(self, fact: Fact) -> str:
        """
        Add a fact (SPO triple) to the table.
        Updates all indexes. Returns fact_id.
        """
        with self._lock:
            self._facts[fact.fact_id] = fact

            # Update indexes
            self._by_subject.setdefault(fact.subject_id, set()).add(fact.fact_id)
            self._by_predicate.setdefault(fact.predicate, set()).add(fact.fact_id)
            self._by_object.setdefault(fact.object_id, set()).add(fact.fact_id)
            if fact.source_paper:
                self._by_paper.setdefault(fact.source_paper, set()).add(fact.fact_id)

        logger.debug(
            f"Added fact [{fact.fact_id}]: "
            f"({fact.subject_id}, {fact.predicate.value}, {fact.object_id}) "
            f"conf={fact.confidence:.2f}"
        )
        return fact.fact_id

    def get_fact(self, fact_id: str) -> Optional[Fact]:
        """Get fact by ID."""
        return self._facts.get(fact_id)

    def remove_fact(self, fact_id: str) -> bool:
        """Remove a fact from the table."""
        fact = self._facts.pop(fact_id, None)
        if fact is None:
            return False

        # Clean indexes
        self._by_subject.get(fact.subject_id, set()).discard(fact_id)
        self._by_predicate.get(fact.predicate, set()).discard(fact_id)
        self._by_object.get(fact.object_id, set()).discard(fact_id)
        if fact.source_paper:
            self._by_paper.get(fact.source_paper, set()).discard(fact_id)

        return True

    # -----------------------------------------------------------------------
    # Query interface (used by Rule Engine)
    # -----------------------------------------------------------------------

    def query(
        self,
        subject_id: Optional[str] = None,
        predicate: Optional[PredicateType] = None,
        object_id: Optional[str] = None,
        source_paper: Optional[str] = None,
        min_confidence: float = 0.0,
        include_inferred: bool = True,
    ) -> List[Fact]:
        """
        Query facts by any combination of S, P, O filters.
        
        This is the main interface consumed by the Rule Engine.
        
        Examples:
            # Find all facts about CNN_Segmentation
            facts = ft.query(subject_id="CNN_Segmentation")
            
            # Find all CONTRADICTS relations
            facts = ft.query(predicate=PredicateType.CONTRADICTS)
            
            # Find what requires high_compute
            facts = ft.query(predicate=PredicateType.REQUIRES_RESOURCE, object_id="high_compute")
        """
        # Start with all fact_ids then intersect
        candidate_ids: Optional[Set[str]] = None

        if subject_id is not None:
            ids = self._by_subject.get(subject_id, set())
            candidate_ids = ids if candidate_ids is None else candidate_ids & ids

        if predicate is not None:
            ids = self._by_predicate.get(predicate, set())
            candidate_ids = ids if candidate_ids is None else candidate_ids & ids

        if object_id is not None:
            ids = self._by_object.get(object_id, set())
            candidate_ids = ids if candidate_ids is None else candidate_ids & ids

        if source_paper is not None:
            ids = self._by_paper.get(source_paper, set())
            candidate_ids = ids if candidate_ids is None else candidate_ids & ids

        # If no filters, return all
        if candidate_ids is None:
            candidate_ids = set(self._facts.keys())

        # Apply remaining filters
        results = []
        for fid in candidate_ids:
            fact = self._facts[fid]
            if fact.confidence < min_confidence:
                continue
            if not include_inferred and fact.is_inferred:
                continue
            results.append(fact)

        return results

    def query_triples(
        self,
        subject_id: Optional[str] = None,
        predicate: Optional[PredicateType] = None,
        object_id: Optional[str] = None,
    ) -> List[Tuple[str, str, str]]:
        """
        Query and return as simple (S, P, O) tuples.
        Convenience method for graph building.
        """
        facts = self.query(subject_id=subject_id, predicate=predicate, object_id=object_id)
        return [(f.subject_id, f.predicate.value, f.object_id) for f in facts]

    # -----------------------------------------------------------------------
    # Contradiction detection
    # -----------------------------------------------------------------------

    def find_contradictions(self) -> List[Tuple[Fact, Fact]]:
        """
        Find pairs of facts that are marked as CONTRADICTS.
        
        Returns list of (fact_a, fact_b) tuples where:
        - fact_a's subject CONTRADICTS fact_b's subject (via a CONTRADICTS fact)
        
        Used by gap detection for "Inkonsistensi" indicator.
        """
        contradiction_facts = self.query(predicate=PredicateType.CONTRADICTS)
        pairs = []
        
        for cf in contradiction_facts:
            # Find the actual findings that are contradicting
            subject_facts = self.query(subject_id=cf.subject_id)
            object_facts = self.query(subject_id=cf.object_id)
            
            if subject_facts and object_facts:
                pairs.append((subject_facts[0], object_facts[0]))
        
        return pairs

    # -----------------------------------------------------------------------
    # Statistics
    # -----------------------------------------------------------------------

    def get_statistics(self) -> Dict[str, Any]:
        """Get table statistics for API response."""
        entity_counts = {}
        for e in self._entities.values():
            key = e.entity_type.value
            entity_counts[key] = entity_counts.get(key, 0) + 1

        predicate_counts = {}
        for p, fids in self._by_predicate.items():
            predicate_counts[p.value] = len(fids)

        inferred_count = sum(1 for f in self._facts.values() if f.is_inferred)

        return {
            "total_entities": len(self._entities),
            "total_facts": len(self._facts),
            "total_inferred_facts": inferred_count,
            "entities_by_type": entity_counts,
            "facts_by_predicate": predicate_counts,
            "papers_indexed": len(self._by_paper),
        }

    def get_all_facts_as_dicts(self) -> List[Dict[str, Any]]:
        """Export all facts as list of dicts (for API serialization)."""
        return [f.to_dict() for f in self._facts.values()]

    def get_facts_for_paper(self, paper_id: str) -> List[Fact]:
        """Get all facts extracted from a specific paper."""
        return self.query(source_paper=paper_id)

    # -----------------------------------------------------------------------
    # Bulk operations
    # -----------------------------------------------------------------------

    def add_facts_bulk(self, facts: List[Fact]) -> int:
        """Add multiple facts at once. Returns count of facts added."""
        count = 0
        for fact in facts:
            self.add_fact(fact)
            count += 1
        logger.info(f"Bulk added {count} facts")
        return count

    def clear(self):
        """Clear all entities and facts."""
        self._entities.clear()
        self._facts.clear()
        self._by_subject.clear()
        self._by_predicate.clear()
        self._by_object.clear()
        self._by_paper.clear()
        logger.info("FactTable cleared")

    def __repr__(self) -> str:
        return (
            f"FactTable(entities={len(self._entities)}, "
            f"facts={len(self._facts)})"
        )
